Fix missing_device_returns_sensible_error test due to changed error
---- missing_device_returns_sensible_error stdout ----
thread 'missing_device_returns_sensible_error' panicked at 'assertion failed: `(left == right)`
  left: `"Error response received from netlink: Unknown error -1 (os error -1)"`,
 right: `"Error response received from netlink: Unknown error -19 (os error -19)"`', tests/enodev.rs:32:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    missing_device_returns_sensible_error

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s