Switch to GitHub Actions for CI
The wireguard-dkms module (version 20200611) was failing to build
against Ubuntu 16.04 and 18.04 on Travis CI. After connecting to the VM
and viewing make logs, I observed the error attached at the end of this
commit. A similar error was also posted on r/WireGuard:

https://www.reddit.com/r/WireGuard/comments/h0tkzt/up_to_date_ubuntu_18044_cannot_compile_wireguard/

For some reason "dist: focal" did not switch Travis CI to use Ubuntu
20.04. Moving to GitHub actions since it supports Ubuntu 20.04 and
appears to be much faster with less effort.

---

DKMS make.log for wireguard-1.0.20200611 for kernel 4.15.0-1037-gcp (x86_64)
Sat Aug 15 20:34:27 UTC 2020
make: Entering directory '/usr/src/linux-headers-4.15.0-1037-gcp'
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/main.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/noise.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/device.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/peer.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/timers.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/queueing.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/send.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/receive.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/socket.o
  CC [M]  /var/lib/dkms/wireguard/1.0.20200611/build/peerlookup.o
/var/lib/dkms/wireguard/1.0.20200611/build/socket.c: In function ‘send6’:
/var/lib/dkms/wireguard/1.0.20200611/build/socket.c:139:20: error: ‘const struct ipv6_stub’ has no member named ‘ipv6_dst_lookup_flow’; did you mean ‘ipv6_dst_lookup’?
   dst = ipv6_stub->ipv6_dst_lookup_flow(sock_net(sock), sock, &fl,
                    ^~~~~~~~~~~~~~~~~~~~
                    ipv6_dst_lookup
scripts/Makefile.build:330: recipe for target '/var/lib/dkms/wireguard/1.0.20200611/build/socket.o' failed
make[1]: *** [/var/lib/dkms/wireguard/1.0.20200611/build/socket.o] Error 1
make[1]: *** Waiting for unfinished jobs....
Makefile:1552: recipe for target '_module_/var/lib/dkms/wireguard/1.0.20200611/build' failed
make: *** [_module_/var/lib/dkms/wireguard/1.0.20200611/build] Error 2
make: Leaving directory '/usr/src/linux-headers-4.15.0-1037-gcp'